### ISSUE TITLE
Hidden elements cannot be validated

### ISSUE THREAD

**Issue by ckihneman** [bmauser/bvalidator#1]
Title pretty much says it all. Hidden elements are skipped when bValidator is initialized on the form. Libraries like [Chosen](https://github.com/harvesthq/chosen) set the select to display none, meaning the element will not be validated.

I forked and updated the code to add a new option to bValidator here: https://github.com/ckihneman/bValidator

It is hidden away pretty well behind the new option, and could help some people out. Consider merging it in via #2 . Here is [a thread of some people running into this same issue](https://groups.google.com/forum/#!topic/bvalidator/La2bkhvVBFE).

**Comment by bmauser** [comment]
Hi, sorry for no replying to this issue, I will not update ver0, but there is `skipValidation` option in the ver1 to set which inputs will be skipped.
