### ISSUE TITLE
Ajax validation doesnt work correctly

### ISSUE THREAD

**Issue by DalerHakimov** [bmauser/bvalidator#12]
Hello,

Basically, I'm trying to implement one of the examples with ajax validation, but no matter what is the result it always does show the validaiton-ajax message, that its wrong.

I have a form which has `data-bvalidator-option-ajax-url="getRecordId.action"` in the header of the form.

Than I have input `<input id="recordId" name="recordId" type="text"  value="$!citizen.recordId" data-bvalidator="digit,ajax,required" data-bvalidator-msg-ajax="The number does exist in the DB. ENter new number" data-fordraft="digit,required" data-bvalidator-modifier="myDigitsModifier"/>`

When I type any numbers, doesnt matter it does exist or no, it always shows a message that The number does exist in the DB.

I do return a simple JSON from the server:

- if it does exist I return `{"recordId":"false"}` which should mean that it does exist and it should not be validated.

- if it DOES NOT exist I return `{"recordId":"ok"}`, which should be validated as OK... but it still gives me an error message that number doest exist.

Any help is appreciated

**Comment by DalerHakimov** [comment]
An error is on line 247.

You have `if (ajaxValidationResult != fn.options.ajaxValid) {` 

Here you are comparing an object `ajaxValidationResult ` which has a value of `Object {recordId: "ok"}` with just an option with a value of `ok`.

In this case, doesnt matter what I pass ok, or anything else, it will always be validated as invalid. I think this is clears bug. I modified it for my use case, but would be nice to have it working for all cases...

**Comment by bmauser** [comment]
Hi, sorry I haven't replied to this till now. There was a bug when `Content-type:application/json` is sent from the server and jQuery returned an object. It should be fixed in v1.0.5, thank you for reporting this.
