### ISSUE TITLE
Not able to negate in Regex Pattern

### ISSUE THREAD

**Issue by eMahtab** [bmauser/bvalidator#7]
Hi bmauser, I'm trying to validate phone number I don't want user to enter 9999999999 so I'm using regex[!(9999999999)] . But its not working. I also tried regex[^(9999999999)] but its not working. Please help me out with this. I cant attach custom function to validate as form data comes in dynamically to the angularJS view.

**Comment by bmauser** [comment]
Hi, try this if you use bvalidator version 0.x: `regex[^((?!9999999999).)*$]`
If you use version 1.x try: `pattern[^((?!9999999999).)*$]` or you can use html5 pattern attribute:
`pattern="^((?!9999999999).)*$"`

**Comment by eMahtab** [comment]
Hi bmauser, I will try that and let you know If that works . Thanks for the time.

**Comment by eMahtab** [comment]
Thanks bmauser, those regex did work. I want to ask you for one more regex, what should be the regex for allowing any number except zero. So 0123.4567 is valid but 0 is not
