### ISSUE TITLE
Can't enable/disable for multi instance bvalidator

### ISSUE THREAD

**Issue by DalerHakimov** [bmauser/bvalidator#8]
I do have 2 instance of bvalidator on my form and 2 buttons. One saves the form when its partially validated the another saves the form when its completely validated. When its completely valitdated it works fine. But when I want to disable the first instance and run the second instance it doesnt work. It does destroy the whole bvalidation instance, instead of destroying only its first instance. More on SO:
http://stackoverflow.com/questions/38090941/how-to-enable-disable-the-2-instance-of-bvalidator

I really would be much appreciated if this can be fixed, or its me doing something wrong.

**Comment by bmauser** [comment]
Hi, I answered on stackoverflow. But maybe I didn't get you right what you want to do, if that is the case, please put somewhere your form, it would be easier if there is an example.

**Comment by DalerHakimov** [comment]
I've added comments on SO, your answer is somewhere acceptable but it's not the right behavior that I'm looking for.

**Comment by bmauser** [comment]
.destroy() should be now fixed in 1.0.3. I also commented on SO.

**Comment by DalerHakimov** [comment]
I've only now had a time to go back and update the validation on our app. Now it works as expected, thanks a lot for upgrading the plugin.
